export enum Marcas {
    'Acura', 'Agrale', 'AlfaRomeo', 'Asia',
    'AMGeneral', 'AstonMartin', 'Audi', 'Adly',
    'Aprilia', 'Atala', 'Amazonas', 'Austin',
    'Apperson', 'AshokLeyland', 'Alpina', 'Adler',
    'Ascari', 'Abarth', 'Autobianchi', 'Aixam',
    'AMG', 'AZLK', 'Avtokam', 'ACMAT',
    'Albion', 'Argyle', 'Askam', 'AsparkOwl',
    'A.D.Tramontana', 'BMW', 'Buggy', 'BRM',
    'Bugre', 'Bugatti', 'Bentley', 'Buick',
    'Baker', 'Biddle', 'Bajaj', 'Bitter',
    'Borgward', 'Briggs', 'Belsize', 'Bertone',
    'Bianchi', 'Brilliance', 'BydAuto', 'Baic',
    'Birrana', 'Brabus', 'Birkin', 'Bailey',
    'Chevrolet', 'Cadillac', 'CBT', 'Chana',
    'Changan', 'Chery', 'Chrysler', 'Citroen',
    'CrossLander', 'Chinkara', 'Caterham', 'Chater-Lea',
    'Covini', 'Caresto', 'Changhe', 'Cizeta',
    'Daewoo', 'Daihatsu', 'Dodge', 'DeTomaso',
    'Ducati', 'Delorean', 'DKW', 'DRMotor',
    'DeLaChapelle', 'Dongfeng', 'DRB', 'Derways',
    'DragonMotors', 'Daimler', 'Datsun', 'Dacia',
    'DoniRosset', 'Effa', 'Engesa', 'Envemo',
    'Eicher', 'Esther', 'Elfin', 'Eagle',
    'Eterniti', 'ERF', 'Elva',
    'Geely', 'GM', 'GreatWall',
    'Gurgel', 'GMC', 'Gorhan',
    'Gumpert', 'Ginetta', 'Geo',
    'GAC', 'Giocattolo', 'Gaz',
    'Genesis', 'Gillet', 'Grinnall',
    'Hafei', 'Honda', 'Hyunday',
    'Harley-Davidson', 'Husqvarna', 'Hummer',
    'Hindustan', 'Hongqi', 'Holden',
    'HSV', 'Hino', 'Harper',
    'HeroMotors', 'Isuzu', 'Iveco',
    'ICMLMotors', 'Infiniti', 'Isdera',
    'Invicta', 'IsottaFraschini', 'Irizar',
    'Innoson', 'Ivema', 'Jeep',
    'Jaguar', 'JPX', 'Jinbei',
    'JAC', 'James&Browne', 'JosseCar',
    'Jiefang', 'Kia', 'Kahena',
    'Kasinski', 'KTM', 'Keinath',
    'Koenigsegg', 'Kamaz', 'Kawasaki',
    'Karma', 'Kaz', 'Karrier',
    'Kantanka', 'Kiira',
    'Lada', 'Lamborghini', 'Lancia',
    'LandRover', 'Lexus', 'Lifan',
    'Lotus', 'Lobini', 'Lincoln',
    'Laferrari', 'Ligier', 'Lagonda',
    'Lucid', 'Luxgen', 'Laraki',
    'Mahindra', 'Maserati', 'Matra',
    'MG', 'Mazda', 'Mclaren',
    'Mercedes-Benz', 'Mercury', 'Miura',
    'Mini', 'Mitsubishi', 'Maruti',
    'Mitsuoka', 'Maybach', 'Microcar',
    'Mack', 'Moskvich', 'Marussia',
    'MAN', 'Marcos', 'Mazzanti',
    'Morris', 'Mustang', 'MAZ',
    'Mobius', 'Nissan', 'Navistar',
    'Nota', 'NamiOkhta', 'Noble',
    'Opel', 'Oldsmobile', 'OhtaJidosha',
    'Otosan', 'ÖAF', 'Peugeot',
    'Plymouth', 'Pontiac', 'Porsche',
    'Puma', 'Polaris', 'Panoz',
    'Premier', 'Prince', 'Pagani',
    'Panhard', 'PGO', 'Pyeonghwa',
    'Proto', 'Perodua', 'Paccar',
    'Pininfarina', 'ParamountAutomotive', 'Proforce',
    'Perana', 'Qvale', 'Qoros',
    'RAM', 'Rely', 'Rover',
    'Renault', 'Rolls-Royce', 'Rootes',
    'Rambler', 'Riley', 'Rossion',
    'RUF', 'Ronart', 'Rimac',
    'SAAB', 'Saturn', 'SEAT',
    'Shineray', 'Smart', 'Ssangyong',
    'Subaru', 'Suzuki', 'Sundown',
    'SinoTruck', 'Scania', 'Scion',
    'Saic', 'Spetsteh', 'Skoda',
    'Shelby', 'Saleen', 'Sterling',
    'SaroukhEl-jamahiriya', 'ShakaNynya', 'TAC',
    'Toyota', 'Troller', 'Tata',
    'Triumph', 'Traxx', 'Tesla',
    'Tatra', 'Trion', 'TheTurtle',
    'Tropical', 'UAZ', 'Unimog',
    'UEV', 'Ultima', 'Uri',
    'URO', 'Volvo', 'Volkswagen',
    'Venturi', 'Volga', 'Vauxhall',
    'Vector', 'Venucia', 'Vulcan',
    'Vomag', 'Vanaja',
    'Wake', 'Walk',
    'Wuyang', 'Wheego',
    'Willeme', 'Wallys',
    'Xbasiralsanayei', 'XBehnam',
    'Yamaha', 'Yale',
    'Yuna', 'Yugo',
    'Yulon', 'Yarovit',
    'Yorkshire', 'Zimmer',
    'ZyleDaewoo', 'Zotye',
    'Zil', 'Zastava',
    'Zolfe', 'Zenvo',
    'Zender', 'Zwicky'
}