version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: veiculo
        ports:
            - "5440:5432"
    app:
        container_name: veiculo-api
        restart: always
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app/
        depends_on:
            - db